name: my_input_component
description: "A new Flutter plugin project."
version: 0.0.1
homepage: "my_input_component"
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  number_text_input_formatter: any
  plugin_platform_interface: any
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
